
name: basicCI

on: 
  workflow_call:
    inputs:
      SOURCE: 
        required: true
        type: string
      TARGET: 
        required: true
        type: string
      ACTION:
        required: true
        type: string

env:
  LD_LIBRARY_PATH: /usr/local/gmssl/lib

jobs:
  sm2Interop_test:
    name: CI for interop
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@main
      with:
          go-version: 1.18
    - uses: actions/checkout@main
      with:
          repository: guanzhi/GmSSL
          path: GMSSL
          ref: master
    - run: SYSTEM=`uname -s` ./config --prefix=/usr/local/gmssl;
      working-directory: GMSSL
    - run: make
      working-directory: GMSSL