
name: sm3
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 3' # https://crontab.guru/#0_0_*_*_3
env:
  LD_LIBRARY_PATH: /usr/local/gmssl/lib
jobs:
  sm3Interop_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@main
      with:
          go-version: 1.18
    - uses: actions/checkout@main
      with:
          repository: guanzhi/GmSSL
          path: GMSSL
          ref: master
    - run: SYSTEM=`uname -s` ./config --prefix=/usr/local/gmssl;
      working-directory: GMSSL
    - run: make
      working-directory: GMSSL
    - run: sudo make install_sw
      working-directory: GMSSL
    - run: go mod vendor
      working-directory: interop
    - run: go test -v util_test.go sm3Interop_test.go
      working-directory: interop
      name: sm3 data interaction check